# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e61ac1274c44a350edd13e3ce4c7c8669a41bfede1bda7b3ec29f7a2ba4a5ab6ced1ad978e30654ff614529ef002e8e0deb9636a1024e0c108369b0db1d607c6

test:
  secret_key_base: c5f5aa642778a4ddb8d574970ae0983de5fedb085110c23e1ab8d19ba1aede2ada58362327962e85f92873e8badfdbdf5681b1ab30989dc812f929e9aa45d159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
